services:
  fastapi_backend:
    build:
      context: ./apps/backend
      target: runtime
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/backend:/app
      - ./apps/backend/data:/app/data:ro
