"""Unexecuted Vietnamese candidate holdout for P2.1R human review.

This module is data only.  It must never import or call Plan V2; the source
was authored without observing Plan V2 candidate outputs.
"""

from __future__ import annotations


ACCEPTED_CANDIDATES = {
    "nutrition": [
        ("Ngày 14/10 tôi trực đêm, hãy đề xuất thực đơn cho phần thời gian còn lại của ngày theo múi giờ Đà Nẵng.", "NUTRITION_READY_OR_CLARIFY"),
        ("Tôi bị dị ứng mè và cần ba bữa vào thứ bảy, đừng gợi ý món có dầu mè.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Lập thực đơn hai ngày cho người không dung nạp lactose, ưu tiên món dễ mang đi làm.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Cho tôi kế hoạch ăn trong chuyến công tác từ 03 đến 05 tháng 11 tại Cần Thơ, không dùng nội tạng.", "NUTRITION_READY_OR_CLARIFY"),
        ("Tôi muốn bữa trưa ít muối nhưng hồ sơ sức khỏe chưa tải xong; hãy nói rõ điều gì còn thiếu.", "NUTRITION_MISSING_CONTEXT"),
        ("Hãy sắp bữa ăn cho người đang có thai và buồn nôn kéo dài.", "NUTRITION_SPECIALIST_GATE"),
        ("Tạo menu ba ngày không có hạt điều và không có nước cốt dừa.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Tôi cần thực đơn một ngày khi đi tàu, chỉ có thể ăn vào 06:30, 12:15 và 20:00.", "NUTRITION_READY_OR_CLARIFY"),
        ("Lên kế hoạch ăn từ Chủ nhật đến thứ ba cho người ăn chay có dùng sữa, tránh đồ chiên.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Đừng suy diễn lượng calo đã ăn của tôi; chỉ lập phần bữa tối dự kiến cho ngày mai.", "NUTRITION_PLANNED_NOT_ACTUAL"),
        ("Tôi có bệnh thận đang điều trị, xin một thực đơn giảm đạm thật nghiêm ngặt.", "NUTRITION_SPECIALIST_GATE"),
        ("Soạn bữa sáng và bữa xế cho ngày 29/02/2028, không dùng mật ong.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Tôi chỉ xác nhận mục tiêu duy trì, chưa cung cấp chiều cao hay cân nặng; nên hỏi tôi gì trước?", "NUTRITION_MISSING_CONTEXT"),
        ("Hãy lập menu ba ngày cho người không ăn thịt đỏ nhưng vẫn ăn gia cầm và trứng.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Tôi cần bữa ăn cho ca sáng bắt đầu lúc 05:00, lịch theo Asia/Ho_Chi_Minh.", "NUTRITION_READY_OR_CLARIFY"),
        ("Đề xuất thực đơn tuần sau, nhưng tôi chưa nói dị ứng có còn hiệu lực hay không.", "NUTRITION_MISSING_CONTEXT"),
        ("Tôi bị rối loạn ăn uống và muốn cắt khẩu phần thật mạnh trong bảy ngày.", "NUTRITION_SPECIALIST_GATE"),
        ("Xếp các bữa cho ngày đầu tháng, không dùng nấm và không lặp món chính trong cùng ngày nếu có lựa chọn.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Tôi ở múi giờ UTC-5 đến hết thứ sáu; hãy xác nhận ngày địa phương trước khi lập thực đơn.", "NUTRITION_READY_OR_CLARIFY"),
        ("Chỉ tạo bản nháp bữa trưa cho cuộc họp ngày 18/12, không lưu bất cứ thứ gì.", "NUTRITION_NO_WRITE_PREVIEW"),
        ("Tôi có hạn chế ăn rau sống sau phẫu thuật gần đây, có cần tư vấn chuyên môn trước không?", "NUTRITION_SPECIALIST_GATE"),
        ("Lên menu hai ngày không dùng đậu nành, kể cả tương và sữa đậu nành.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Hãy lập ba bữa cho ngày mai; tôi không rõ cân nặng trong hồ sơ là mới hay cũ.", "NUTRITION_MISSING_CONTEXT"),
        ("Tôi ăn halal và muốn thực đơn một ngày bằng các món có tham chiếu thực phẩm chuẩn.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Tạo kế hoạch cho cuối tuần nhưng không coi việc tôi đặt món là đã tiêu thụ.", "NUTRITION_PLANNED_NOT_ACTUAL"),
        ("Tôi đang cho con bú và muốn giảm cân rất nhanh; hãy xử lý yêu cầu này an toàn.", "NUTRITION_SPECIALIST_GATE"),
        ("Gợi ý bữa sáng ngày 01/01 với dị ứng kiwi, không tự thay bằng món chưa có mã danh mục.", "NUTRITION_CANONICAL_CONSTRAINT"),
        ("Tôi muốn các bữa phù hợp ngày chuyển múi giờ từ Tokyo về Việt Nam, cần làm rõ ngày nào trước?", "NUTRITION_READY_OR_CLARIFY"),
        ("Đừng ghi nhận nước uống hôm nay; tôi chỉ hỏi thực đơn ngày kia không có hành tây.", "NUTRITION_NO_WRITE_PREVIEW"),
        ("Tôi bị hạn chế dịch do tim mạch, xin một thực đơn chi tiết theo lượng nước.", "NUTRITION_SPECIALIST_GATE"),
    ],
    "workout_single_session": [
        ("Tôi có 25 phút ở sân chung cư và chỉ mang dây mini-band, lập buổi tập dự kiến.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tạo một buổi tập nhẹ cho ngày mai, nhưng cổ tay phải của tôi đang đau chưa được đánh giá.", "WORKOUT_SAFETY_GATE"),
        ("Ở khách sạn tôi có xe đạp tại chỗ, 35 phút, mục tiêu vận động vừa phải chứ không ghi thành buổi đã hoàn thành.", "WORKOUT_PLANNED_NOT_ACTUAL"),
        ("Tôi có ghế vững và tạ ấm 8 kg, muốn lịch một buổi 40 phút tại nhà.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tôi ghi mục tiêu là sức bền nhưng không rõ là tim mạch hay cơ bắp; hãy hỏi để phân biệt.", "WORKOUT_MISSING_CONTEXT"),
        ("Lập một buổi tại phòng tập vào 06:00, tránh mọi động tác quá đầu vì vai trái khó chịu.", "WORKOUT_SAFETY_GATE"),
        ("Tôi chỉ có sàn trống và khăn, hãy đưa ra bản nháp vận động 20 phút cho người mới.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tôi muốn tập sau một cơn đau ngực mới xảy ra, hãy ưu tiên an toàn thay vì kê bài.", "WORKOUT_SAFETY_GATE"),
        ("Hãy tạo phiên tập cho người dùng có kinh nghiệm chưa xác minh, thời lượng 50 phút.", "WORKOUT_MISSING_CONTEXT"),
        ("Tôi có máy chèo thuyền và dây kháng lực ở văn phòng, dành 30 phút vào trưa thứ tư.", "WORKOUT_READY_OR_CLARIFY"),
        ("Đừng tự ghi RPE hay số lần lặp thực tế; tôi chỉ muốn xem một buổi tập nháp 45 phút.", "WORKOUT_PLANNED_NOT_ACTUAL"),
        ("Tôi vừa bong gân mắt cá chân và muốn bài chân cường độ cao tối nay.", "WORKOUT_SAFETY_GATE"),
        ("Lập buổi 30 phút với bóng tập yoga và tường, không giả định tôi có tạ.", "WORKOUT_READY_OR_CLARIFY"),
        ("Mục tiêu của tôi là tăng sức mạnh nhưng tiền sử tập luyện đang ở trạng thái không tải được.", "WORKOUT_MISSING_CONTEXT"),
        ("Tôi cần một buổi sáng sớm ở công viên, có xà đơn công cộng, giới hạn 35 phút.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tôi bị choáng khi gắng sức gần đây, hãy cho biết vì sao không nên tự tạo buổi nặng.", "WORKOUT_SAFETY_GATE"),
        ("Thiết kế bản xem trước cho một buổi mobility 15 phút sau khi ngồi máy bay dài.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tôi nói 'tập bền' nhưng không cho biết thiết bị, thời lượng, hay bối cảnh; cần hỏi tối thiểu gì?", "WORKOUT_MISSING_CONTEXT"),
        ("Tôi có dây treo cửa và ghế, hãy chuẩn bị một buổi 40 phút nhưng không tự lưu nó.", "WORKOUT_NO_WRITE_PREVIEW"),
        ("Sau chấn thương lưng chưa rõ chẩn đoán, tôi muốn deadlift nặng ngay hôm nay.", "WORKOUT_SAFETY_GATE"),
        ("Lập buổi tập 55 phút trong khu tập ngoài trời có bậc thang và lan can chắc chắn.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tôi có hồ sơ giới tính tập luyện bị mâu thuẫn giữa hai nguồn; đừng suy diễn hệ số hay mục tiêu.", "WORKOUT_MISSING_CONTEXT"),
        ("Tạo buổi thư giãn 20 phút với thảm dày cho ngày làm việc căng thẳng.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tôi bị tê lan xuống cánh tay khi vận động, hãy xử lý như một cổng an toàn.", "WORKOUT_SAFETY_GATE"),
        ("Tôi có máy elliptic, giới hạn 28 phút, và chỉ muốn lịch dự kiến cho thứ hai.", "WORKOUT_PLANNED_NOT_ACTUAL"),
        ("Lập một buổi khởi động trước khi leo núi; thiết bị chỉ là balô nhẹ và băng ghế.", "WORKOUT_READY_OR_CLARIFY"),
        ("Tôi chưa xác nhận có đang mang thai hay không nhưng muốn tập cường độ cao.", "WORKOUT_SAFETY_GATE"),
        ("Hãy xem trước buổi 32 phút ở nhà với dây dài; chưa cần ghi vào lịch.", "WORKOUT_NO_WRITE_PREVIEW"),
        ("Tôi có tiền sử huyết áp nhưng trạng thái hiện tại không rõ, có đủ dữ kiện để kê buổi không?", "WORKOUT_MISSING_CONTEXT"),
        ("Tạo buổi vận động nhẹ 18 phút khi chỉ có khoảng trống cạnh bàn làm việc.", "WORKOUT_READY_OR_CLARIFY"),
    ],
    "weekly_workout_scheduling": [
        ("Tuần 09/11 tôi rảnh thứ hai, thứ năm và chủ nhật; xếp đúng ba buổi, mỗi buổi 35 phút.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tôi chỉ có thể tập sau 21:00 vào thứ ba và thứ sáu, hãy tạo hai slot theo giờ địa phương.", "WEEKLY_EXACT_SCHEDULE"),
        ("Xếp bốn buổi từ 01 đến 07/12, nhưng thứ tư là ngày không được tập.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tôi cần ba buổi tuần tới nhưng chỉ đưa một ngày rảnh; hãy yêu cầu làm rõ thay vì tự bịa ngày.", "WEEKLY_MISSING_AVAILABILITY"),
        ("Trong tuần có đổi múi giờ từ UTC+7 sang UTC+1, tôi chọn ngày 10, 12 và 14 theo lịch điểm đến.", "WEEKLY_TIMEZONE_EXACT"),
        ("Đặt hai buổi liên tiếp thứ bảy và chủ nhật vì đó là lựa chọn duy nhất của tôi.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tôi muốn năm buổi nhưng chỉ có thứ hai, thứ tư và thứ sáu trống.", "WEEKLY_INSUFFICIENT_AVAILABILITY"),
        ("Lên lịch ba buổi, riêng thứ năm có 20 phút còn hai ngày kia mỗi ngày 50 phút.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tôi nói 'trong tuần này' khi giờ hiện tại sát nửa đêm UTC; hãy xác nhận tuần theo Asia/Ho_Chi_Minh.", "WEEKLY_TIMEZONE_EXACT"),
        ("Sắp hai slot tập tại nhà vào ngày 06 và 09 tháng 3, không suy ra buổi đã tập.", "WEEKLY_PLANNED_NOT_ACTUAL"),
        ("Tôi rảnh mọi ngày trừ thứ hai, hãy đề xuất ba slot và ghi rõ đó là heuristic sản phẩm.", "WEEKLY_HEURISTIC_LABEL"),
        ("Tôi yêu cầu ba buổi vào thứ hai, thứ hai và thứ sáu; hãy phát hiện ngày trùng.", "WEEKLY_INVALID_REQUEST"),
        ("Xếp lịch từ thứ sáu đến thứ hai tuần sau với ba buổi, thứ bảy không rảnh.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tôi chỉ có 30 phút hôm nay và 60 phút chủ nhật, hãy giữ đúng hai ngân sách thời gian.", "WEEKLY_EXACT_SCHEDULE"),
        ("Không có dữ liệu hồi phục thật; hãy tạo ba slot kế hoạch chứ không kết luận tôi đã hồi phục.", "WEEKLY_PLANNED_NOT_ACTUAL"),
        ("Tôi muốn hai buổi trong kỳ 28/12 đến 03/01, có thể tập thứ ba và thứ bảy.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tạo lịch bốn buổi với các ngày ưu tiên là 02, 04, 06, 08; ngày 06 lại bị báo bận.", "WEEKLY_CONFLICT_CLARIFY"),
        ("Tuần này tôi có ba ngày trống nhưng không cung cấp thời lượng; hãy hỏi thay vì mặc định phút.", "WEEKLY_MISSING_AVAILABILITY"),
        ("Xếp một buổi duy nhất vào thứ năm, không biến nó thành lịch tập hoàn thành.", "WEEKLY_PLANNED_NOT_ACTUAL"),
        ("Tôi xin ba buổi trong khoảng chỉ có hai ngày lịch hợp lệ, hãy từ chối có mã lý do rõ ràng.", "WEEKLY_INSUFFICIENT_AVAILABILITY"),
        ("Theo lịch Việt Nam, ngày đầu kỳ là thứ hai 04/05; tôi chọn thứ hai, tư và bảy.", "WEEKLY_EXACT_SCHEDULE"),
        ("Lập lịch hai buổi khi tôi bay qua đường đổi ngày quốc tế, trước hết phải làm rõ ngày địa phương hiển thị.", "WEEKLY_TIMEZONE_EXACT"),
        ("Tôi rảnh thứ ba và thứ năm, muốn hai buổi gym 45 phút, không cần tự quyết bài tập.", "WEEKLY_E4_DELEGATION"),
        ("Đừng thêm một buổi thứ tư chỉ vì khoảng cách đều; tôi chỉ yêu cầu thứ hai và thứ sáu.", "WEEKLY_EXACT_SCHEDULE"),
        ("Xếp ba session có lịch lần lượt 25, 40 và 55 phút vào 11, 13, 16 tháng 8.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tôi muốn 'cuối tuần' nhưng không nói ở quốc gia nào; cần làm rõ múi giờ và ngày.", "WEEKLY_TIMEZONE_EXACT"),
        ("Hãy tạo bốn slot trong bảy ngày khi chỉ biết số buổi, và nêu rõ lý do các ngày được chọn.", "WEEKLY_HEURISTIC_LABEL"),
        ("Tôi có hai ngày không khả dụng chồng lên hai ngày ưu tiên; đừng âm thầm thay đổi yêu cầu.", "WEEKLY_CONFLICT_CLARIFY"),
        ("Xếp ba buổi từ 30/04 đến 02/05, mỗi buổi 30 phút, theo lịch địa phương Việt Nam.", "WEEKLY_EXACT_SCHEDULE"),
        ("Tôi cần hai session nhưng E4 trả trạng thái chưa sẵn sàng cho một slot; không được tự bù nội dung tập.", "WEEKLY_E4_DELEGATION"),
    ],
    "combined_health": [
        ("Tôi muốn xem bản nháp ăn và vận động cho ba ngày đi công tác, không được cộng trừ calo giữa hai phần.", "COMBINED_REFERENCE_ONLY"),
        ("Hãy tạo container kế hoạch sức khỏe cho 07 đến 09/09 nhưng phần tập vẫn thiếu dữ liệu E4.", "COMBINED_CHILD_MISSING"),
        ("Tôi đã có bản ăn ngày mai; hãy liên kết nó với lịch đi bộ dự kiến chứ không ghi nhận đã vận động.", "COMBINED_REFERENCE_ONLY"),
        ("Soạn khung kết hợp theo múi giờ Bangkok, bữa ăn và slot tập phải giữ tham chiếu riêng.", "COMBINED_REFERENCE_ONLY"),
        ("Tôi chỉ muốn đổi giờ buổi tập trong kế hoạch kết hợp, không được tính lại thực đơn.", "COMBINED_ISOLATED_REVISION"),
        ("Một bản ăn và một bản tập có ngày bắt đầu khác nhau, hãy yêu cầu làm rõ thay vì ghép im lặng.", "COMBINED_CHILD_MISSING"),
        ("Tạo xem trước kế hoạch kết hợp cuối tuần, không tự lưu hay kích hoạt bất kỳ phần nào.", "COMBINED_NO_WRITE_PREVIEW"),
        ("Tôi muốn kiểm tra lịch ăn và tập có cùng owner không trước khi tạo container.", "COMBINED_OWNER_BOUND"),
        ("Hãy liên kết hai revision đã biết, giữ nguyên hash của từng revision con.", "COMBINED_REFERENCE_IDENTITY"),
        ("Tôi nói giảm năng lượng vì buổi tập bị hủy, nhưng chỉ muốn sửa lịch tập; không bù trừ tự động.", "COMBINED_ISOLATED_REVISION"),
        ("Tạo khung ăn và vận động một ngày khi thông tin dinh dưỡng chưa tải xong.", "COMBINED_CHILD_MISSING"),
        ("Tôi cần xem kế hoạch kết hợp qua nửa đêm tại Vancouver; xác nhận phạm vi ngày địa phương.", "COMBINED_REFERENCE_ONLY"),
        ("Hãy mở revision kết hợp của người khác mà không đưa owner xác thực.", "COMBINED_OWNER_BOUND"),
        ("Tôi xác nhận lưu phần ăn nhưng chưa xác nhận phần tập; đừng coi container là đã lưu đầy đủ.", "COMBINED_NO_WRITE_PREVIEW"),
        ("Cho tôi một container chỉ để trình bày liên kết giữa meal plan và workout plan, không trộn item của hai domain.", "COMBINED_REFERENCE_ONLY"),
    ],
    "revision_lifecycle_concurrency_adversarial": [
        ("Tạm dừng revision đang ACTIVE của tôi, dùng đúng revision id vừa hiển thị.", "LIFECYCLE_EXACT_OWNER_WRITE"),
        ("Tiếp tục revision đã PAUSED sau khi tôi xác nhận lại, không tạo bản kế hoạch mới.", "LIFECYCLE_EXACT_OWNER_WRITE"),
        ("Hai điện thoại cùng sửa cùng một revision; thao tác dùng số revision cũ phải báo xung đột.", "LIFECYCLE_STALE_CONFLICT"),
        ("Lưu lại chính xác preview có hash tôi vừa xác nhận, không sinh lại menu khác.", "LIFECYCLE_IDENTITY_CHAIN"),
        ("Dùng lại request id của lần lưu trước nhưng đổi revision id, hệ thống phải fail-closed.", "LIFECYCLE_IDEMPOTENCY"),
        ("Kích hoạt revision dinh dưỡng trùng kỳ với revision ACTIVE cũ của cùng tôi; xử lý overlap theo giao dịch.", "LIFECYCLE_OVERLAP"),
        ("Tôi muốn hủy draft vừa mở, không được ghi nó thành actual meal hay actual workout.", "LIFECYCLE_NO_ACTUAL_WRITE"),
        ("Đọc revision có plan id hợp lệ nhưng revision id thuộc owner khác.", "LIFECYCLE_OWNER_BOUND"),
        ("Thử đổi status bằng principal anonymous; yêu cầu phải bị từ chối trước khi ghi dữ liệu.", "LIFECYCLE_OWNER_BOUND"),
        ("Hash trong xác nhận của tôi thiếu một ký tự; không được lưu kiểu best effort.", "LIFECYCLE_IDENTITY_CHAIN"),
        ("Pending action đã hết hạn nhưng người dùng bấm xác nhận muộn; không được tạo write mới.", "LIFECYCLE_STALE_CONFLICT"),
        ("Tôi yêu cầu hoàn tất revision PAUSED của chính mình, giữ nguyên identity của revision.", "LIFECYCLE_EXACT_OWNER_WRITE"),
        ("Một retry mạng gửi lại đúng action id và đúng revision sau khi server đã commit; kết quả phải idempotent.", "LIFECYCLE_IDEMPOTENCY"),
        ("Hãy sửa 'món đó' khi cuộc hội thoại có hai meal item cùng loại; cần yêu cầu tham chiếu rõ ràng.", "LIFECYCLE_STALE_CONFLICT"),
        ("Tôi muốn activate một revision chưa SAVE; không được âm thầm bỏ qua lifecycle.", "LIFECYCLE_EXACT_OWNER_WRITE"),
    ],
}


DEFERRED_CANDIDATES = [
    ("nutrition", "Tôi muốn ăn sạch hơn vào ngày mai.", "REJECTED_AMBIGUOUS_INTENT"),
    ("nutrition", "Lập menu lành mạnh khi có việc bận.", "REJECTED_AMBIGUOUS_INTENT"),
    ("nutrition", "Ăn thế nào để đẹp hơn trong tuần tới?", "REJECTED_AMBIGUOUS_INTENT"),
    ("nutrition", "Hôm nay tôi nên ăn gì cho tốt?", "REJECTED_AMBIGUOUS_INTENT"),
    ("nutrition", "Tạo thực đơn phù hợp với cơ thể tôi.", "REJECTED_INSUFFICIENT_ORACLE"),
    ("nutrition", "Tôi muốn một kế hoạch ăn tuyệt vời.", "REJECTED_INSUFFICIENT_ORACLE"),
    ("workout_single_session", "Cho tôi bài tập tốt nhất.", "REJECTED_AMBIGUOUS_INTENT"),
    ("workout_single_session", "Tôi muốn khỏe hơn thật nhanh.", "REJECTED_AMBIGUOUS_INTENT"),
    ("workout_single_session", "Hãy tập cho tôi ngay.", "REJECTED_INSUFFICIENT_CONTEXT"),
    ("workout_single_session", "Bài nào đốt mỡ hiệu quả nhất?", "REJECTED_SAFETY_AND_SEMANTICS"),
    ("workout_single_session", "Sắp xếp buổi tập phù hợp với tôi.", "REJECTED_INSUFFICIENT_CONTEXT"),
    ("workout_single_session", "Tôi cần vận động nhưng chưa biết gì cả.", "REJECTED_AMBIGUOUS_INTENT"),
    ("weekly_workout_scheduling", "Sắp lịch tập tuần này cho hợp lý.", "REJECTED_AMBIGUOUS_INTENT"),
    ("weekly_workout_scheduling", "Tôi muốn tập nhiều hơn tuần tới.", "REJECTED_INSUFFICIENT_CONTEXT"),
    ("weekly_workout_scheduling", "Xếp lịch tối ưu nhất cho tôi.", "REJECTED_INSUFFICIENT_ORACLE"),
    ("weekly_workout_scheduling", "Tôi có lịch bận, hãy tự lo phần còn lại.", "REJECTED_AMBIGUOUS_INTENT"),
    ("weekly_workout_scheduling", "Sắp các buổi tập ở ngày phù hợp.", "REJECTED_INSUFFICIENT_CONTEXT"),
    ("weekly_workout_scheduling", "Lịch tập nào cũng được miễn nhanh.", "REJECTED_AMBIGUOUS_INTENT"),
    ("combined_health", "Kết hợp ăn uống và thể thao cho tôi.", "REJECTED_AMBIGUOUS_INTENT"),
    ("combined_health", "Làm kế hoạch sức khỏe toàn diện nhất.", "REJECTED_INSUFFICIENT_ORACLE"),
    ("combined_health", "Tôi muốn khỏe mạnh từ tuần sau.", "REJECTED_AMBIGUOUS_INTENT"),
    ("combined_health", "Ghép mọi kế hoạch lại với nhau.", "REJECTED_UNSAFE_REFERENCE_SCOPE"),
    ("combined_health", "Cân bằng ăn và tập thật hoàn hảo.", "REJECTED_AMBIGUOUS_INTENT"),
    ("combined_health", "Tạo chương trình sống lành mạnh.", "REJECTED_INSUFFICIENT_CONTEXT"),
    ("revision_lifecycle_concurrency_adversarial", "Lưu giúp tôi cái vừa rồi.", "REJECTED_AMBIGUOUS_REFERENCE"),
    ("revision_lifecycle_concurrency_adversarial", "Sửa kế hoạch cũ cho hợp lý.", "REJECTED_AMBIGUOUS_REFERENCE"),
    ("revision_lifecycle_concurrency_adversarial", "Bật kế hoạch lên nhé.", "REJECTED_AMBIGUOUS_REFERENCE"),
    ("revision_lifecycle_concurrency_adversarial", "Xóa bản không cần thiết.", "REJECTED_AMBIGUOUS_REFERENCE"),
    ("revision_lifecycle_concurrency_adversarial", "Thử lại thao tác vừa lỗi.", "REJECTED_INSUFFICIENT_IDEMPOTENCY_CONTEXT"),
    ("revision_lifecycle_concurrency_adversarial", "Đổi món hôm trước đi.", "REJECTED_AMBIGUOUS_REFERENCE"),
]


def candidate_rows() -> list[dict[str, str | bool]]:
    rows: list[dict[str, str | bool]] = []
    for area, candidates in ACCEPTED_CANDIDATES.items():
        for index, (prompt, oracle_profile) in enumerate(candidates, start=1):
            rows.append({
                "candidate_id": f"p2r-{area}-{index:03d}",
                "area": area,
                "prompt": prompt,
                "oracle_profile": oracle_profile,
                "proposed_disposition": "ACCEPT_AFTER_HUMAN_REVIEW",
                "acceptance_eligible": True,
            })
    for index, (area, prompt, reason) in enumerate(DEFERRED_CANDIDATES, start=1):
        rows.append({
            "candidate_id": f"p2r-deferred-{index:03d}",
            "area": area,
            "prompt": prompt,
            "oracle_profile": reason,
            "proposed_disposition": "NOT_SELECTED",
            "acceptance_eligible": False,
        })
    return rows
