"""Controlled adaptive recipe knowledge for N3.

The package is intentionally staging-first. It reads the canonical food layer
but has no writer for frozen research assets or the production dish catalog.
"""

from .contracts import (
    CandidateStatus,
    FeedbackRejectionReason,
    FeedbackEventType,
    IngredientScaleClass,
    MappingStatus,
    PromotionClass,
    RecipeCandidate,
    RecipeEvidenceBundle,
    TrustDomain,
)
from .engine import (
    AdaptiveRecipeError,
    CanonicalIngredientMapper,
    RecipePortionFitter,
    RecipeQualityGate,
    build_recipe_candidate,
)
from .repository import (
    AdaptiveRecipeRepository,
    CanonicalRecipeWriter,
    PromotionPolicy,
    build_promotion_evidence_scorecard,
    compute_preference_score,
)
from .discovery import (
    ApprovedExternalRecipeProvider,
    DiscoveryReason,
    LocalCatalogProvider,
    RecipeDiscoveryRequest,
)
from .recommendation import AdaptiveRecommendationPipeline
from .intelligence import (
    CandidateFeatures,
    CandidateSourceType,
    CatalogGapDetector,
    CatalogGapObservation,
    LearningQualityMetrics,
    ConfirmedPreference,
    DeterministicExplorationPolicy,
    PortionLearning,
    PortionObservation,
    PreferenceDimension,
    PreferenceProfileBuilder,
    RecommendationContext,
    RecommendationMemoryEntry,
    RecommendationRankerV2,
    RecommendationReplayEvaluator,
    ShadowBanditPolicy,
    calculate_learning_quality_metrics,
    hard_safety_invariants,
)
from .development_scenarios import N32DevelopmentScenario, development_scenarios
from .shadow_evaluation import (
    ComparisonStatus,
    N33DevelopmentScenario,
    ObservedFeedbackMetrics,
    ShadowComparisonResult,
    ShadowComparisonScenario,
    evaluate_shadow_comparison,
    frozen_ranking_baselines,
    n3_3_development_scenarios,
    observed_feedback_metrics,
)
from .external import (
    ControlledSearchDiscoveryProvider,
    ExternalCandidateFactory,
    ExternalRecipeAcquisitionService,
    FetchStrategy,
    HttpRecipeFetcher,
    PlaywrightCliEdgeTransport,
    PlaywrightRecipeFetcher,
    RecipeSearchQuery,
    StructuredRecipeExtractionService,
    TheMealDbSearchProvider,
)

__all__ = [
    "AdaptiveRecipeError",
    "AdaptiveRecipeRepository",
    "AdaptiveRecommendationPipeline",
    "ApprovedExternalRecipeProvider",
    "CandidateStatus",
    "CandidateFeatures",
    "CandidateSourceType",
    "CatalogGapDetector",
    "CatalogGapObservation",
    "CanonicalIngredientMapper",
    "CanonicalRecipeWriter",
    "ControlledSearchDiscoveryProvider",
    "FeedbackEventType",
    "FeedbackRejectionReason",
    "DiscoveryReason",
    "ExternalCandidateFactory",
    "ExternalRecipeAcquisitionService",
    "FetchStrategy",
    "HttpRecipeFetcher",
    "IngredientScaleClass",
    "LocalCatalogProvider",
    "LearningQualityMetrics",
    "MappingStatus",
    "PromotionClass",
    "PromotionPolicy",
    "PlaywrightCliEdgeTransport",
    "PlaywrightRecipeFetcher",
    "RecipeCandidate",
    "RecipeDiscoveryRequest",
    "RecipeEvidenceBundle",
    "RecipePortionFitter",
    "RecipeSearchQuery",
    "RecipeQualityGate",
    "ConfirmedPreference",
    "ComparisonStatus",
    "DeterministicExplorationPolicy",
    "N32DevelopmentScenario",
    "N33DevelopmentScenario",
    "ObservedFeedbackMetrics",
    "PortionLearning",
    "PortionObservation",
    "PreferenceDimension",
    "PreferenceProfileBuilder",
    "RecommendationContext",
    "RecommendationMemoryEntry",
    "RecommendationRankerV2",
    "RecommendationReplayEvaluator",
    "ShadowBanditPolicy",
    "ShadowComparisonResult",
    "ShadowComparisonScenario",
    "calculate_learning_quality_metrics",
    "development_scenarios",
    "evaluate_shadow_comparison",
    "frozen_ranking_baselines",
    "hard_safety_invariants",
    "n3_3_development_scenarios",
    "observed_feedback_metrics",
    "TrustDomain",
    "StructuredRecipeExtractionService",
    "TheMealDbSearchProvider",
    "build_recipe_candidate",
    "build_promotion_evidence_scorecard",
    "compute_preference_score",
]
