"""Render auditable Vietnam-first acceptance evidence without changing frozen data."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4];DATA=ROOT/"apps/backend/data/research_acceptance_vn";DOCS=ROOT/"docs/evaluation";RES=ROOT/"evaluation/results/acceptance_vn"
def read(p):return json.loads(p.read_text(encoding="utf-8"))
def main():
 m=read(DATA/"manifests/acceptance_corpus_manifest.json");a=read(DATA/"manifests/acceptance_candidate_audit.json");e=read(ROOT/"evaluation/acceptance_vn/manifest.json");r=read(RES/"metrics.json");reg=read(DATA/"source_registry.json")
 schema={"source_id","publisher","title","source_url","download_url","version","publication_date","accessed_at","license","license_url","reuse_status","attribution_required","raw_artifact_path","raw_sha256","parser","parser_version","language","jurisdiction","authority_level","record_count_raw","record_count_included","record_count_excluded","exclusion_reason"};prov=all(schema<=set(x) for x in reg["sources"])
 vn_norm=r["by_report_domain"]["VN_NORMATIVE"];general=(r["by_report_domain"]["GLOBAL_HEALTH"]["hit_at_5"]+r["by_report_domain"]["EXERCISE_CATALOG"]["hit_at_5"]+r["by_report_domain"]["FOREIGN_FOOD"]["hit_at_5"])/3
 payload={"ACCEPTANCE_CORPUS_VERSION":m["corpus_version"],"ACCEPTANCE_CORPUS_HASH":m["corpus_hash"],"ACCEPTANCE_CORPUS_CHUNKS":m["record_count"],"VIETNAM_OFFICIAL_SOURCE_COUNT":4,"VIETNAM_SOURCE_RECORD_COUNT":a["vn_source_record_count"],"VIETNAM_SOURCE_RECORD_PERCENT":a["vn_source_record_percent"],"VIETNAM_RELEVANT_RECORD_COUNT":a["vn_relevant_record_count"],"VIETNAM_RELEVANT_RECORD_PERCENT":a["vn_relevant_record_percent"],"VN_FOOD":a["domain_counts"]["VN_FOOD"],"VN_DISH":a["domain_counts"]["VN_DISH"],"VN_NUTRIENT_REQUIREMENT":a["domain_counts"]["VN_NUTRIENT_REQUIREMENT"],"VN_MICRONUTRIENT":a["domain_counts"]["VN_MICRONUTRIENT"],"VN_NUTRITION_GUIDELINE":a["domain_counts"]["VN_NUTRITION_GUIDELINE"],"VN_PHYSICAL_ACTIVITY":a["domain_counts"]["VN_PHYSICAL_ACTIVITY"],"VN_BODY_METRIC":a["domain_counts"]["VN_BODY_METRIC"],"INTERNATIONAL_SUPPLEMENTAL":m["record_count"]-a["vn_source_record_count"],"RECORDS_BY_CHATBOT_INTENT":a["records_by_chatbot_intent"],"EXCLUDED_LOW_CHATBOT_UTILITY":a["excluded_low_chatbot_utility"],"FINAL_EVAL_CASES":e["case_count"],"FINAL_VIETNAM_CONTEXT_CASES":e["vietnam_context_cases"],"VN_HIT_AT_1":vn_norm["hit_at_1"],"VN_HIT_AT_3":vn_norm["hit_at_3"],"VN_HIT_AT_5":vn_norm["hit_at_5"],"VN_MRR":vn_norm["mrr"],"GENERAL_HIT_AT_5":round(general,4),"NO_EVIDENCE_CORRECTNESS":r["overall"]["no_evidence_correctness"],"LICENSE_AUDIT_PASS":"NO","PROVENANCE_AUDIT_PASS":"YES" if prov else "NO","CONTAMINATION_PASS":"YES" if e["contamination_pass"] else "NO","READY_FOR_RESEARCH_REPORT":"NO","READY_FOR_ACCEPTANCE_DEMO":"NO","NO_COMMIT":"YES","NO_PUSH":"YES"}
 RES.mkdir(parents=True,exist_ok=True);(RES/"acceptance_evidence.json").write_text(json.dumps(payload,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8")
 DOCS.mkdir(parents=True,exist_ok=True)
 (DOCS/"vietnam_first_acceptance_corpus.md").write_text("# Vietnam-first acceptance corpus\n\n"+f"Frozen corpus: `{m['corpus_version']}` ({m['record_count']} chunks), hash `{m['corpus_hash']}`.\n\n"+"## Source precedence\n\n1. Vietnam Ministry/NIN normative guidance\n2. Global public-health guidance\n3. Foreign-government guidance\n4. Other verified reference\n\n"+"## Chatbot utility gate\n\n"+json.dumps({"records_by_chatbot_intent":a["records_by_chatbot_intent"],"excluded_low_chatbot_utility":a["excluded_low_chatbot_utility"],"utility_exclusions":"apps/backend/data/research_acceptance_vn/manifests/utility_exclusions.jsonl"},ensure_ascii=False,indent=2)+"\n\nVietnam-source records are 656 (13.24%); Vietnam-relevant records are 646 (13.04%). Copyright/reuse for Vietnamese FCT and NIN source prose remains limited; only project-authored factual normalizations were stored, so redistribution clearance is still required.\n",encoding="utf-8")
 (DOCS/"vietnam_first_acceptance_results.md").write_text("# Vietnam-first acceptance results\n\n```json\n"+json.dumps(payload,ensure_ascii=False,indent=2)+"\n```\n\nThe corpus prioritizes Vietnamese authoritative nutrition guidance and Vietnamese food data in deterministic normative retrieval. It is not acceptance-ready: frozen VN normative Hit@5 is 0.3 and VN food Hit@5 is 0.0. No post-score tuning was performed.\n",encoding="utf-8")
 print(json.dumps({"ok":True,**payload},ensure_ascii=False))
if __name__=="__main__":main()
