"""Synthetic, development-only oracle set. No research cases are included."""

from __future__ import annotations

from dataclasses import dataclass

from .contracts import DataStatus, Intent, RagPolicy, SourceId, ValidatorId


SCENARIO_SET_VERSION = "context-planner-development-v1"


@dataclass(frozen=True, slots=True)
class DevelopmentScenario:
    scenario_id: str
    query: str
    expected_primary_intent: Intent
    expected_secondary_intents: tuple[Intent, ...]
    expected_required_sources: tuple[SourceId, ...]
    expected_forbidden_sources: tuple[SourceId, ...]
    expected_rag_policy: RagPolicy
    expected_tools: tuple[str, ...]
    expected_validators: tuple[ValidatorId, ...]
    source_statuses: tuple[tuple[SourceId, DataStatus], ...]


@dataclass(frozen=True, slots=True)
class _ManualGroup:
    group_id: str
    queries: tuple[str, str, str]
    primary: Intent
    secondary: tuple[Intent, ...]
    required: tuple[SourceId, ...]
    forbidden: tuple[SourceId, ...]
    rag: RagPolicy
    tools: tuple[str, ...]
    validators: tuple[ValidatorId, ...]


S = SourceId
I = Intent
V = ValidatorId
RF = RagPolicy.FORBIDDEN

# Each group below is a manually authored engineering oracle. The expected
# labels are intentionally stored alongside the human-written paraphrases and
# are never generated by the classifier, matrix, or an LLM.
_GROUPS = (
    _ManualGroup("remaining_calories", ("Hôm nay tôi còn bao nhiêu calo?", "How many calories are remaining today?", "Calo còn lại trong ngày là bao nhiêu?"), I.DAILY_NUTRITION_STATUS, (), (S.DAILY_NUTRITION, S.CANONICAL_NUTRITION), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("calculate_tdee", "get_today_meals"), (V.NUMERIC_CONSISTENCY, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("remaining_protein", ("Hôm nay tôi còn bao nhiêu protein?", "How much protein is remaining today?", "Lượng đạm còn lại trong ngày?"), I.DAILY_NUTRITION_STATUS, (), (S.DAILY_NUTRITION, S.CANONICAL_NUTRITION), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("calculate_tdee", "get_today_meals"), (V.NUMERIC_CONSISTENCY, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("overeating", ("Hôm nay tôi có ăn quá nhiều calo không?", "Am I overeating today?", "Đánh giá xem hôm nay tôi có vượt mức không."), I.MEAL_OR_DIET_EVALUATION, (), (S.NUTRITION_SAFETY, S.DAILY_NUTRITION, S.CANONICAL_NUTRITION), (S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("calculate_tdee", "get_active_plan", "get_today_meals"), (V.NUMERIC_CONSISTENCY, V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("vietnamese_dinner", ("Gợi ý bữa tối Việt Nam giàu protein.", "Recommend a high-protein Vietnamese dinner.", "Đề xuất món ăn Việt nhiều đạm cho bữa tối."), I.MEAL_RECOMMENDATION, (), (S.PROFILE, S.NUTRITION_SAFETY, S.CONFIRMED_MEMORY, S.DISH_DATABASE), (S.MEAL_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_active_plan", "get_today_meals", "get_user_profile", "suggest_dish"), (V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("post_workout_meal", ("Gợi ý bữa ăn sau tập cho tôi.", "Recommend a post workout meal.", "Sau tập tôi nên ăn gì, gợi ý một món."), I.MEAL_RECOMMENDATION, (), (S.PROFILE, S.NUTRITION_SAFETY, S.CONFIRMED_MEMORY, S.DISH_DATABASE), (S.MEAL_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_active_plan", "get_today_meals", "get_user_profile", "suggest_dish"), (V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("seafood_restriction", ("Tôi không ăn hải sản.", "I have a seafood restriction.", "Ghi nhớ rằng tôi dị ứng hải sản."), I.PROFILE_OR_CONSTRAINT_UPDATE, (), (S.PROFILE,), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_user_profile",), (V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.PERSISTENCE_CONFIRMATION)),
    _ManualGroup("vegetarian_restriction", ("Tôi ăn chay.", "I am vegetarian.", "Chế độ ăn của tôi là vegan."), I.PROFILE_OR_CONSTRAINT_UPDATE, (), (S.PROFILE,), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_user_profile",), (V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.PERSISTENCE_CONFIRMATION)),
    _ManualGroup("menu_compatibility", ("Thực đơn hôm nay có phù hợp mục tiêu không?", "Does today's menu fit my goal?", "Đánh giá bữa ăn hôm nay có đáp ứng mục tiêu."), I.MEAL_OR_DIET_EVALUATION, (), (S.NUTRITION_SAFETY, S.DAILY_NUTRITION, S.CANONICAL_NUTRITION), (S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("calculate_tdee", "get_active_plan", "get_today_meals"), (V.NUMERIC_CONSISTENCY, V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("weight_trend", ("Xu hướng cân nặng 7 ngày của tôi thế nào?", "Show my seven-day weight trend.", "Cân nặng thay đổi ra sao trong tuần qua?"), I.WEIGHT_PROGRESS, (), (S.WEIGHT_HISTORY,), (S.MEAL_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_weight_history",), (V.NUMERIC_CONSISTENCY, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("active_plan", ("Kế hoạch hiện tại của tôi thế nào?", "What is my active plan status?", "Tôi đang theo kế hoạch nào?"), I.PLAN_MANAGEMENT, (), (S.ACTIVE_PLAN,), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_active_plan",), (V.PERSISTENCE_CONFIRMATION, V.CURRENT_STATE_FRESHNESS, V.PLAN_CONSISTENCY)),
    _ManualGroup("previous_dish", ("Tại sao bạn vừa gợi ý món đó?", "Why was that previous dish recommended?", "Vì sao trước đó bạn đề xuất món này?"), I.FOLLOWUP_EXPLANATION, (), (S.RECENT_CONVERSATION,), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.MEDICAL_EVIDENCE), RagPolicy.OPTIONAL, (), (V.NUMERIC_CONSISTENCY, V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT)),
    _ManualGroup("fibre", ("Chất xơ là gì và có lợi ích gì?", "What are the benefits of dietary fibre?", "Tại sao cơ thể cần fiber?"), I.GENERAL_NUTRITION_KNOWLEDGE, (), (S.RAG,), (S.DAILY_NUTRITION, S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.MEDICAL_EVIDENCE), RagPolicy.REQUIRED, ("query_rag",), (V.EVIDENCE_GROUNDING,)),
    _ManualGroup("medical_evidence", ("Bằng chứng y khoa về chất xơ và bệnh tiểu đường?", "What clinical evidence links fibre and diabetes?", "Có nghiên cứu lâm sàng nào về dinh dưỡng cho bệnh tiểu đường?"), I.EVIDENCE_HEALTH_QUESTION, (), (S.NUTRITION_SAFETY, S.MEDICAL_EVIDENCE), (S.DAILY_NUTRITION, S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG), RagPolicy.REQUIRED, ("search_medical_knowledge",), (V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.EVIDENCE_GROUNDING)),
    _ManualGroup("food_lookup", ("Dinh dưỡng của 100g ức gà?", "What is the nutrition of an avocado?", "Bao nhiêu calo trong một quả chuối?"), I.FOOD_NUTRITION_LOOKUP, (), (S.FOOD_DATABASE,), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("search_food_nutrition",), (V.NUMERIC_CONSISTENCY,)),
    _ManualGroup("log_meal", ("Ghi lại bữa ăn trưa của tôi.", "Log my lunch meal.", "Lưu bữa tối này vào nhật ký meal."), I.APP_ACTION, (), (), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("log_meal",), (V.PERSISTENCE_CONFIRMATION,)),
    _ManualGroup("log_weight", ("Ghi lại cân nặng 68 kg.", "Log my weight as 68 kg.", "Lưu cân nặng hôm nay là 68kg."), I.APP_ACTION, (), (), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("log_weight",), (V.PERSISTENCE_CONFIRMATION,)),
    _ManualGroup("workout", ("Gợi ý bài tập cho hôm nay.", "Recommend a workout for today.", "Đề xuất lịch tập luyện hôm nay."), I.WORKOUT_RECOMMENDATION, (), (S.PROFILE, S.TODAY_EXERCISE), (S.MEAL_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_today_exercises", "get_user_profile", "suggest_workout"), (V.CURRENT_STATE_FRESHNESS, V.PLAN_CONSISTENCY)),
    _ManualGroup("sleep_stress", ("Giấc ngủ và stress ảnh hưởng phục hồi thế nào?", "How do sleep and stress affect recovery?", "Tôi căng thẳng và mệt mỏi, đánh giá lối sống giúp tôi."), I.EXERCISE_RECOVERY, (), (S.TODAY_EXERCISE, S.LIFESTYLE), (S.MEAL_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("get_lifestyle_logs", "get_today_exercises", "get_today_meals"), (V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.CURRENT_STATE_FRESHNESS)),
    _ManualGroup("casual", ("Xin chào!", "Hello, how are you?", "Cảm ơn bạn nhé."), I.SMALLTALK_OR_OTHER, (), (), (S.NUTRITION_SAFETY, S.DAILY_NUTRITION, S.TODAY_EXERCISE, S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.WEIGHT_HISTORY, S.LIFESTYLE, S.ACTIVE_PLAN, S.SAVED_MEALS, S.CONFIRMED_MEMORY, S.RAG, S.MEDICAL_EVIDENCE, S.CANONICAL_NUTRITION), RF, (), ()),
    _ManualGroup("multi_intent", ("Hôm nay còn bao nhiêu protein và gợi ý bữa tối?", "How many calories remain today, and recommend dinner.", "Calo còn lại trong ngày rồi đề xuất một bữa ăn."), I.DAILY_NUTRITION_STATUS, (I.MEAL_RECOMMENDATION,), (S.PROFILE, S.NUTRITION_SAFETY, S.DAILY_NUTRITION, S.CONFIRMED_MEMORY, S.DISH_DATABASE, S.CANONICAL_NUTRITION), (S.MEAL_HISTORY, S.EXERCISE_HISTORY, S.RAG, S.MEDICAL_EVIDENCE), RF, ("calculate_tdee", "get_active_plan", "get_today_meals", "get_user_profile", "suggest_dish"), (V.NUMERIC_CONSISTENCY, V.DIETARY_CONSTRAINT, V.ALLERGY_CONSTRAINT, V.CURRENT_STATE_FRESHNESS)),
)


DEVELOPMENT_SCENARIOS = tuple(
    DevelopmentScenario(
        scenario_id=f"{group.group_id}_{index + 1}", query=query,
        expected_primary_intent=group.primary, expected_secondary_intents=group.secondary,
        expected_required_sources=group.required, expected_forbidden_sources=group.forbidden,
        expected_rag_policy=group.rag, expected_tools=group.tools,
        expected_validators=group.validators,
        source_statuses=tuple((source, DataStatus.NOT_LOADED) for source in group.required),
    )
    for group in _GROUPS
    for index, query in enumerate(group.queries)
)


__all__ = ["DEVELOPMENT_SCENARIOS", "DevelopmentScenario", "SCENARIO_SET_VERSION"]
